[package]
name = "boisu-core"
version = "0.1.0"
license = "MIT"
authors = ["Justice Almanzar <superdash993@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
cpal = "0.14.2"
rtp = "0.6.8"
opus = "0.3.0"
samplerate = "0.2.4"
crossbeam-channel = "0.5.6"

[dependencies.core-macros]
path = "../core-macros"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
