[package]
name = "boisu-core"
version = "0.1.0"
license = "MIT"
authors = ["Justice Almanzar <superdash993@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
tokio = "1.24.1"

[dependencies.core-macros]
path = "../core-macros"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
