[package]
name = "voice-engine-native"
version = "0.1.0"
license = "MIT"
authors = ["Justice Almanzar <superdash993@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
napi = "2"
napi-derive = "2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
